### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by napolly1** [napolly1/laphasildryer#5]
Rata-rata pertanyaan yang ada:

1. "Iki ngisi ne neng bagian endi Mas?"
2. Hasil e belum automated itungan m3 ne
3. sama mending dipisah per ukuran kayak punya grup B, mereka juga jelas jadine
4. Iki Pendanaan Ready, Share rekening buat bikin domain

**Comment by danilaudza** [comment]
1. Maksudnya how
2 n 3 di pull req #6 https://napolly1.github.io/laphasildryer/#/test

@napolly1

**Comment by danilaudza** [comment]
Lanjut dijadikan halaman depan atau tidak?

@napolly1

**Comment by napolly1** [comment]
Boleh MsDn, Ini baru mau coba trial ngisi

**Comment by danilaudza** [comment]
Oke menunggu feedback dulu berarti

**Comment by danilaudza** [comment]
Done di domain
